name: cloud_bug
description: Bug.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.3

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: 2.13.1
  firebase_auth: 4.6.2
  cloud_firestore: 4.8.0
  
  # bad boy below
  android_intent_plus: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
